rabbitmq:
  image: rabbitmq:3-management
  environment:
   - "RABBITMQ_NODENAME=my-rabbit"
  ports:
   - "5672:5672"
   - "15672:15672"

sftp:
  image: atmoz/sftp
  command: fred:password:1001
  volumes:
   - tests/sshd_config:/etc/ssh/sshd_config:rw
   - tests/uploads:/home/fred/tests:rw
   - examples/uploads:/home/fred/examples:rw
  ports:
   - "10022:22"
